### ISSUE TITLE
包含 , 的文本css样式会被正则表达式replace成;

### ISSUE THREAD

**Issue by lintakejs** [Aisen60/vant-theme#8]
<img width="751" alt="企业微信截图_93f77c6b-9b8e-492b-8837-a8a92d248294" src="https://github.com/Aisen60/vant-theme/assets/16040354/2d68ce5d-7fcc-446f-b129-d69641865a7d">

**Comment by aisen60** [comment]
@lintakejs 感谢反馈，我尽快修复哈~
